<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\{User,Role,Course,Tsp,Round,Batch,Student,BatchStudent,Subject,Module,CompetencyUnit,Element,Question,QuestionOption,ExamSet,Exam};
class BackendWorkflowTest extends TestCase {
    use RefreshDatabase;
    private function admin(): User { /** @var User $u */ $u=User::factory()->create(); $r=Role::create(['name'=>'SUPER_ADMIN']); $u->roles()->attach($r); return $u; }
    private function context(): array { $course=Course::create(['code'=>'C-'.uniqid(),'name'=>'Course','duration_months'=>6,'status'=>'ACTIVE']); $t=Tsp::create(['code'=>'T-'.uniqid(),'name'=>'TSP','status'=>'ACTIVE']); $r=Round::create(['code'=>'R-'.uniqid(),'name'=>'Round','status'=>'ACTIVE']); $b=Batch::create(['course_id'=>$course->id,'tsp_id'=>$t->id,'round_id'=>$r->id,'shift'=>'M','batch_number'=>1,'start_date'=>now()->toDateString(),'status'=>'RUNNING']); $s=Subject::create(['course_id'=>$course->id,'name'=>'Subject','status'=>'ACTIVE']); $m=Module::create(['subject_id'=>$s->id,'name'=>'Module','status'=>'ACTIVE']); $cu=CompetencyUnit::create(['module_id'=>$m->id,'course_id'=>$course->id,'name'=>'CU','status'=>'ACTIVE']); $e=Element::create(['competency_unit_id'=>$cu->id,'name'=>'Element']); return compact('course','b','s','m','cu','e'); }
    public function test_user_without_admin_role_is_rejected(): void { /** @var User $u */ $u=User::factory()->create(); $this->actingAs($u,'sanctum')->getJson('/api/v1/admin/courses')->assertStatus(403)->assertJsonPath('success',false); }
    public function test_batch_capacity_is_enforced(): void { $admin=$this->admin(); $c=$this->context(); for($i=0;$i<15;$i++){ $student=Student::create(['student_id'=>'S'.$i,'name'=>'Student '.$i,'date_of_birth'=>'2000-01-01','status'=>'ACTIVE']); BatchStudent::create(['batch_id'=>$c['b']->id,'student_id'=>$student->id,'assigned_at'=>now(),'status'=>'ACTIVE']); } $sixteenth=Student::create(['student_id'=>'S16','name'=>'Student 16','date_of_birth'=>'2000-01-01','status'=>'ACTIVE']); $this->actingAs($admin,'sanctum')->postJson('/api/v1/admin/batches/'.$c['b']->id.'/students',['student_id'=>$sixteenth->id,'status'=>'ACTIVE'])->assertStatus(422)->assertJsonPath('success',false); }
    public function test_student_login_is_minimal_and_secure(): void { $c=$this->context(); $student=Student::create(['student_id'=>'STU-1','name'=>'Student','date_of_birth'=>'2000-01-01','status'=>'ACTIVE']); BatchStudent::create(['batch_id'=>$c['b']->id,'student_id'=>$student->id,'assigned_at'=>now(),'status'=>'ACTIVE']); $response=$this->postJson('/api/v1/student/login',['student_id'=>'STU-1','date_of_birth'=>'2000-01-01'])->assertOk()->assertJsonPath('success',true); $this->assertArrayNotHasKey('date_of_birth',$response->json('data')); $this->assertArrayHasKey('token',$response->json('data')); }
    public function test_attempt_generates_exactly_25_questions_and_persists_order(): void { $admin=$this->admin(); $c=$this->context(); $student=Student::create(['student_id'=>'STU-2','name'=>'Student','date_of_birth'=>'2000-01-01','status'=>'ACTIVE']); BatchStudent::create(['batch_id'=>$c['b']->id,'student_id'=>$student->id,'assigned_at'=>now(),'status'=>'ACTIVE']); for($i=1;$i<=25;$i++){ $q=Question::create(['course_id'=>$c['course']->id,'subject_id'=>$c['s']->id,'module_id'=>$c['m']->id,'competency_unit_id'=>$c['cu']->id,'element_id'=>$c['e']->id,'question_code'=>'Q-'.$i.'-'.uniqid(),'question_text'=>'Question '.$i,'question_type'=>'SINGLE_CORRECT','difficulty'=>'MEDIUM','marks'=>1,'status'=>'ACTIVE']); QuestionOption::create(['question_id'=>$q->id,'option_key'=>'A','option_text'=>'Yes','is_correct'=>true,'option_order'=>1]); QuestionOption::create(['question_id'=>$q->id,'option_key'=>'B','option_text'=>'No','is_correct'=>false,'option_order'=>2]); } $set=ExamSet::create(['batch_id'=>$c['b']->id,'name'=>'Set','status'=>'ACTIVE']); $exam=Exam::create(['exam_set_id'=>$set->id,'exam_number'=>'E1','exam_title'=>'Exam','exam_type'=>'MCQ','mode'=>'ONLINE','status'=>'STARTED','duration'=>30,'max_marks'=>25,'pass_marks'=>13]); $exam->subjects()->attach($c['s']->id); $exam->modules()->attach($c['m']->id); $exam->competencyUnits()->attach($c['cu']->id); $token=$this->postJson('/api/v1/student/login',['student_id'=>'STU-2','date_of_birth'=>'2000-01-01'])->json('data.token'); $response=$this->withHeader('Authorization','Bearer '.$token)->postJson('/api/v1/student/exams/'.$exam->id.'/start')->assertCreated()->assertJsonPath('success',true); $this->assertCount(25,$response->json('data.questions')); $this->assertCount(25,$response->json('data.questions')); $this->assertArrayNotHasKey('is_correct',$response->json('data.questions.0.options.0')); $this->actingAs($admin,'sanctum')->postJson('/api/v1/admin/attempts/1/process-result')->assertStatus(422); }
}
