<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('roles',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('description')->nullable(),$t->timestamps()]);
 Schema::create('permissions',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('description')->nullable(),$t->timestamps()]);
 Schema::create('role_permissions',fn(Blueprint $t)=>[$t->foreignId('role_id')->constrained()->cascadeOnDelete(),$t->foreignId('permission_id')->constrained()->cascadeOnDelete(),$t->primary(['role_id','permission_id'])]);
 Schema::create('user_roles',fn(Blueprint $t)=>[$t->foreignId('user_id')->constrained()->cascadeOnDelete(),$t->foreignId('role_id')->constrained()->cascadeOnDelete(),$t->primary(['user_id','role_id'])]);
 Schema::create('courses',fn(Blueprint $t)=>[$t->id(),$t->string('code')->unique(),$t->string('name'),$t->unsignedInteger('duration_months'),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('tsps',fn(Blueprint $t)=>[$t->id(),$t->string('code')->unique(),$t->string('name'),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('rounds',fn(Blueprint $t)=>[$t->id(),$t->string('code')->unique(),$t->string('name'),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('batches',fn(Blueprint $t)=>[$t->id(),$t->foreignId('course_id')->constrained()->restrictOnDelete(),$t->foreignId('tsp_id')->constrained()->restrictOnDelete(),$t->foreignId('round_id')->constrained()->restrictOnDelete(),$t->string('shift'),$t->unsignedInteger('batch_number'),$t->date('start_date'),$t->date('end_date')->nullable(),$t->string('status')->index(),$t->timestamps(),$t->unique(['course_id','tsp_id','round_id','shift','batch_number'])]);
 Schema::create('students',fn(Blueprint $t)=>[$t->id(),$t->string('student_id')->unique(),$t->string('name'),$t->date('date_of_birth'),$t->string('email')->nullable(),$t->string('status')->index(),$t->unsignedInteger('failed_login_attempts')->default(0),$t->dateTime('locked_until')->nullable(),$t->timestamps()]);
 Schema::create('batch_students',fn(Blueprint $t)=>[$t->id(),$t->foreignId('batch_id')->constrained()->restrictOnDelete(),$t->foreignId('student_id')->constrained()->restrictOnDelete(),$t->dateTime('assigned_at'),$t->string('status')->index(),$t->unique(['batch_id','student_id','assigned_at'])]);
 Schema::create('subjects',fn(Blueprint $t)=>[$t->id(),$t->foreignId('course_id')->constrained()->restrictOnDelete(),$t->string('name'),$t->string('status')->index(),$t->timestamps(),$t->unique(['course_id','name'])]);
 Schema::create('modules',fn(Blueprint $t)=>[$t->id(),$t->foreignId('subject_id')->constrained()->restrictOnDelete(),$t->string('name'),$t->string('status')->index(),$t->timestamps(),$t->unique(['subject_id','name'])]);
 Schema::create('competency_units',fn(Blueprint $t)=>[$t->id(),$t->foreignId('module_id')->constrained()->restrictOnDelete(),$t->foreignId('course_id')->constrained()->restrictOnDelete(),$t->string('name'),$t->string('status')->index(),$t->timestamps(),$t->unique(['module_id','name'])]);
 Schema::create('elements',fn(Blueprint $t)=>[$t->id(),$t->foreignId('competency_unit_id')->constrained()->restrictOnDelete(),$t->string('name'),$t->timestamps(),$t->unique(['competency_unit_id','name'])]);
 Schema::create('questions',fn(Blueprint $t)=>[$t->id(),$t->foreignId('course_id')->constrained()->restrictOnDelete(),$t->foreignId('subject_id')->constrained()->restrictOnDelete(),$t->foreignId('module_id')->constrained()->restrictOnDelete(),$t->foreignId('competency_unit_id')->constrained()->restrictOnDelete(),$t->foreignId('element_id')->constrained()->restrictOnDelete(),$t->string('question_code')->unique(),$t->text('question_text'),$t->string('question_type'),$t->string('difficulty'),$t->decimal('marks',8,2),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('question_options',fn(Blueprint $t)=>[$t->id(),$t->foreignId('question_id')->constrained()->restrictOnDelete(),$t->string('option_key',10),$t->text('option_text'),$t->boolean('is_correct')->default(false),$t->unsignedInteger('option_order'),$t->timestamps(),$t->unique(['question_id','option_key'])]);
 Schema::create('question_imports',fn(Blueprint $t)=>[$t->id(),$t->foreignId('uploaded_by')->constrained('users')->restrictOnDelete(),$t->string('file_name'),$t->string('file_path'),$t->unsignedInteger('total_rows')->default(0),$t->unsignedInteger('successful_rows')->default(0),$t->unsignedInteger('failed_rows')->default(0),$t->unsignedInteger('duplicate_rows')->default(0),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('question_import_rows',fn(Blueprint $t)=>[$t->id(),$t->foreignId('import_id')->constrained('question_imports')->cascadeOnDelete(),$t->unsignedInteger('row_number'),$t->foreignId('question_id')->nullable()->constrained('questions')->nullOnDelete(),$t->json('raw_data'),$t->string('status'),$t->text('error_message')->nullable(),$t->timestamps()]);
 Schema::create('exam_sets',fn(Blueprint $t)=>[$t->id(),$t->foreignId('batch_id')->constrained()->restrictOnDelete(),$t->string('code')->nullable(),$t->string('name'),$t->string('status')->index(),$t->timestamps()]);
 Schema::create('exams',fn(Blueprint $t)=>[$t->id(),$t->foreignId('exam_set_id')->constrained()->restrictOnDelete(),$t->string('exam_number'),$t->string('exam_title'),$t->string('exam_type'),$t->string('mode'),$t->string('status')->index(),$t->unsignedInteger('duration'),$t->decimal('max_marks',8,2),$t->decimal('pass_marks',8,2),$t->dateTime('start_at')->nullable(),$t->dateTime('end_at')->nullable(),$t->timestamps(),$t->unique(['exam_set_id','exam_number'])]);
 Schema::create('exam_subjects',fn(Blueprint $t)=>[$t->foreignId('exam_id')->constrained()->cascadeOnDelete(),$t->foreignId('subject_id')->constrained()->restrictOnDelete(),$t->primary(['exam_id','subject_id'])]);
 Schema::create('exam_modules',fn(Blueprint $t)=>[$t->foreignId('exam_id')->constrained()->cascadeOnDelete(),$t->foreignId('module_id')->constrained()->restrictOnDelete(),$t->primary(['exam_id','module_id'])]);
 Schema::create('exam_competency_units',fn(Blueprint $t)=>[$t->foreignId('exam_id')->constrained()->cascadeOnDelete(),$t->foreignId('competency_unit_id')->constrained()->restrictOnDelete(),$t->primary(['exam_id','competency_unit_id'])]);
 Schema::create('student_exam_attempts',fn(Blueprint $t)=>[$t->id(),$t->foreignId('student_id')->constrained()->restrictOnDelete(),$t->foreignId('exam_id')->constrained()->restrictOnDelete(),$t->string('status')->index(),$t->dateTime('started_at'),$t->dateTime('expires_at'),$t->dateTime('submitted_at')->nullable(),$t->timestamps(),$t->unique(['student_id','exam_id'])]);
 Schema::create('exam_attempt_questions',fn(Blueprint $t)=>[$t->id(),$t->foreignId('attempt_id')->constrained('student_exam_attempts')->cascadeOnDelete(),$t->foreignId('question_id')->constrained()->restrictOnDelete(),$t->unsignedInteger('question_order'),$t->json('question_snapshot'),$t->timestamps(),$t->unique(['attempt_id','question_id']),$t->unique(['attempt_id','question_order'])]);
 Schema::create('exam_answers',fn(Blueprint $t)=>[$t->id(),$t->foreignId('attempt_id')->constrained('student_exam_attempts')->cascadeOnDelete(),$t->foreignId('exam_attempt_question_id')->constrained()->cascadeOnDelete(),$t->json('selected_options'),$t->dateTime('answered_at'),$t->timestamps(),$t->unique(['attempt_id','exam_attempt_question_id'])]);
 Schema::create('exam_results',fn(Blueprint $t)=>[$t->id(),$t->foreignId('attempt_id')->constrained('student_exam_attempts')->restrictOnDelete(),$t->foreignId('student_id')->constrained()->restrictOnDelete(),$t->foreignId('exam_id')->constrained()->restrictOnDelete(),$t->unsignedInteger('correct_answers'),$t->unsignedInteger('wrong_answers'),$t->unsignedInteger('unanswered_questions'),$t->decimal('total_marks',8,2),$t->decimal('percentage',5,2),$t->string('status'),$t->dateTime('processed_at'),$t->timestamps(),$t->unique('attempt_id')]);
 Schema::create('exam_violations',fn(Blueprint $t)=>[$t->id(),$t->foreignId('attempt_id')->constrained('student_exam_attempts')->restrictOnDelete(),$t->string('type'),$t->json('metadata')->nullable(),$t->dateTime('occurred_at'),$t->timestamps(),$t->index(['attempt_id','type','created_at'])]);
 Schema::create('audit_logs',fn(Blueprint $t)=>[$t->id(),$t->string('actor_type')->nullable(),$t->unsignedBigInteger('actor_id')->nullable(),$t->string('event'),$t->string('auditable_type')->nullable(),$t->unsignedBigInteger('auditable_id')->nullable(),$t->json('payload')->nullable(),$t->ipAddress('ip_address')->nullable(),$t->string('user_agent',500)->nullable(),$t->dateTime('created_at')->useCurrent(),$t->index(['actor_type','actor_id']),$t->index(['auditable_type','auditable_id'])]);
 }
 public function down(): void { foreach(['audit_logs','exam_violations','exam_results','exam_answers','exam_attempt_questions','student_exam_attempts','exam_competency_units','exam_modules','exam_subjects','exams','exam_sets','question_import_rows','question_imports','question_options','questions','elements','competency_units','modules','subjects','batch_students','students','batches','rounds','tsps','courses','user_roles','role_permissions','permissions','roles'] as $t) Schema::dropIfExists($t); }
};
